### ISSUE TITLE
Add a documentation on how to use it in front end

### ISSUE THREAD

**Issue by SalahAdDin** [nicolashmln/strapi-plugin-responsive-image#4]
Hi, i am using this plugin for my custom website(a blog) and i got bad numbers on performance, One of the reasons is the image size.

Looking at the [recommendations](https://web.dev/serve-responsive-images/) I can find some trick to help with it and they are related to image responsiveness; i know this plugin create different images for different sizes but it is not very clear for me how could i used this.

I would be great if you add some examples of it. thanks!

**Comment by nicolashmln** [comment]
Hi, indeed it's more a problem related to your frontend. I'm not sure putting an example in the readme will help because there is too much use cases.

I could recommend to read those articles:
- https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images
- https://www.smashingmagazine.com/2014/05/responsive-images-done-right-guide-picture-srcset/

Once you defined what width and height your images will have, you can go back to the plugin and set the different formats
